# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/stephane/Code/CL/2023/OctaSplit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/stephane/Code/CL/2023/OctaSplit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.26.0/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stephane/Code/CL/2023/OctaSplit/CMakeFiles /Users/stephane/Code/CL/2023/OctaSplit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stephane/Code/CL/2023/OctaSplit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/stephane/Code/CL/2023/OctaSplit/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OctaSplit

# Build rule for target.
OctaSplit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OctaSplit
.PHONY : OctaSplit

# fast build rule for target.
OctaSplit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/build
.PHONY : OctaSplit/fast

Source/Main.o: Source/Main.cpp.o
.PHONY : Source/Main.o

# target to build an object file
Source/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/Source/Main.cpp.o
.PHONY : Source/Main.cpp.o

Source/Main.i: Source/Main.cpp.i
.PHONY : Source/Main.i

# target to preprocess a source file
Source/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/Source/Main.cpp.i
.PHONY : Source/Main.cpp.i

Source/Main.s: Source/Main.cpp.s
.PHONY : Source/Main.s

# target to generate assembly for a file
Source/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/Source/Main.cpp.s
.PHONY : Source/Main.cpp.s

_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.o: _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.o

# target to build an object file
_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.o

_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.i: _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.i

_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.s: _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.mm.s

_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.o: _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.o

# target to build an object file
_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.o

_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.i: _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.i

_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.s: _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.mm.s

_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.o: _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.o

# target to build an object file
_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.o

_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.i: _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.i

_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.s: _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.mm.s

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.o: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.o

# target to build an object file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.o

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.i: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.i

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.s: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.mm.s

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.o: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.o

# target to build an object file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.o

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.i: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.i

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.s: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.cpp.s

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o

# target to build an object file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.o

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.i

_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s: _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s
.PHONY : _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.cpp.s

_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.o: _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.o

# target to build an object file
_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.o
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.o

_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.i: _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.i

# target to preprocess a source file
_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.i
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.i

_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.s: _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.s
.PHONY : _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.mm.s

_deps/juce-src/modules/juce_core/juce_core.o: _deps/juce-src/modules/juce_core/juce_core.mm.o
.PHONY : _deps/juce-src/modules/juce_core/juce_core.o

# target to build an object file
_deps/juce-src/modules/juce_core/juce_core.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_core/juce_core.mm.o
.PHONY : _deps/juce-src/modules/juce_core/juce_core.mm.o

_deps/juce-src/modules/juce_core/juce_core.i: _deps/juce-src/modules/juce_core/juce_core.mm.i
.PHONY : _deps/juce-src/modules/juce_core/juce_core.i

# target to preprocess a source file
_deps/juce-src/modules/juce_core/juce_core.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_core/juce_core.mm.i
.PHONY : _deps/juce-src/modules/juce_core/juce_core.mm.i

_deps/juce-src/modules/juce_core/juce_core.s: _deps/juce-src/modules/juce_core/juce_core.mm.s
.PHONY : _deps/juce-src/modules/juce_core/juce_core.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_core/juce_core.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_core/juce_core.mm.s
.PHONY : _deps/juce-src/modules/juce_core/juce_core.mm.s

_deps/juce-src/modules/juce_data_structures/juce_data_structures.o: _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.o

# target to build an object file
_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.o
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.o

_deps/juce-src/modules/juce_data_structures/juce_data_structures.i: _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.i

# target to preprocess a source file
_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.i
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.i

_deps/juce-src/modules/juce_data_structures/juce_data_structures.s: _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.s
.PHONY : _deps/juce-src/modules/juce_data_structures/juce_data_structures.mm.s

_deps/juce-src/modules/juce_events/juce_events.o: _deps/juce-src/modules/juce_events/juce_events.mm.o
.PHONY : _deps/juce-src/modules/juce_events/juce_events.o

# target to build an object file
_deps/juce-src/modules/juce_events/juce_events.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_events/juce_events.mm.o
.PHONY : _deps/juce-src/modules/juce_events/juce_events.mm.o

_deps/juce-src/modules/juce_events/juce_events.i: _deps/juce-src/modules/juce_events/juce_events.mm.i
.PHONY : _deps/juce-src/modules/juce_events/juce_events.i

# target to preprocess a source file
_deps/juce-src/modules/juce_events/juce_events.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_events/juce_events.mm.i
.PHONY : _deps/juce-src/modules/juce_events/juce_events.mm.i

_deps/juce-src/modules/juce_events/juce_events.s: _deps/juce-src/modules/juce_events/juce_events.mm.s
.PHONY : _deps/juce-src/modules/juce_events/juce_events.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_events/juce_events.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_events/juce_events.mm.s
.PHONY : _deps/juce-src/modules/juce_events/juce_events.mm.s

_deps/juce-src/modules/juce_graphics/juce_graphics.o: _deps/juce-src/modules/juce_graphics/juce_graphics.mm.o
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.o

# target to build an object file
_deps/juce-src/modules/juce_graphics/juce_graphics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_graphics/juce_graphics.mm.o
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.mm.o

_deps/juce-src/modules/juce_graphics/juce_graphics.i: _deps/juce-src/modules/juce_graphics/juce_graphics.mm.i
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.i

# target to preprocess a source file
_deps/juce-src/modules/juce_graphics/juce_graphics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_graphics/juce_graphics.mm.i
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.mm.i

_deps/juce-src/modules/juce_graphics/juce_graphics.s: _deps/juce-src/modules/juce_graphics/juce_graphics.mm.s
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_graphics/juce_graphics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_graphics/juce_graphics.mm.s
.PHONY : _deps/juce-src/modules/juce_graphics/juce_graphics.mm.s

_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.o: _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.o

# target to build an object file
_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.o
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.o

_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.i: _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.i

# target to preprocess a source file
_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.i
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.i

_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.s: _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.s
.PHONY : _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.mm.s

_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.o: _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.o

# target to build an object file
_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.o
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.o

_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.i: _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.i

# target to preprocess a source file
_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.i
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.i

_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.s: _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.s

# target to generate assembly for a file
_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctaSplit.dir/build.make CMakeFiles/OctaSplit.dir/_deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.s
.PHONY : _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.mm.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... OctaSplit"
	@echo "... Source/Main.o"
	@echo "... Source/Main.i"
	@echo "... Source/Main.s"
	@echo "... _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.o"
	@echo "... _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.i"
	@echo "... _deps/juce-src/modules/juce_audio_basics/juce_audio_basics.s"
	@echo "... _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.o"
	@echo "... _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.i"
	@echo "... _deps/juce-src/modules/juce_audio_devices/juce_audio_devices.s"
	@echo "... _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.o"
	@echo "... _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.i"
	@echo "... _deps/juce-src/modules/juce_audio_formats/juce_audio_formats.s"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.o"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.i"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors.s"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.o"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.i"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_ara.s"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.o"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.i"
	@echo "... _deps/juce-src/modules/juce_audio_processors/juce_audio_processors_lv2_libs.s"
	@echo "... _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.o"
	@echo "... _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.i"
	@echo "... _deps/juce-src/modules/juce_audio_utils/juce_audio_utils.s"
	@echo "... _deps/juce-src/modules/juce_core/juce_core.o"
	@echo "... _deps/juce-src/modules/juce_core/juce_core.i"
	@echo "... _deps/juce-src/modules/juce_core/juce_core.s"
	@echo "... _deps/juce-src/modules/juce_data_structures/juce_data_structures.o"
	@echo "... _deps/juce-src/modules/juce_data_structures/juce_data_structures.i"
	@echo "... _deps/juce-src/modules/juce_data_structures/juce_data_structures.s"
	@echo "... _deps/juce-src/modules/juce_events/juce_events.o"
	@echo "... _deps/juce-src/modules/juce_events/juce_events.i"
	@echo "... _deps/juce-src/modules/juce_events/juce_events.s"
	@echo "... _deps/juce-src/modules/juce_graphics/juce_graphics.o"
	@echo "... _deps/juce-src/modules/juce_graphics/juce_graphics.i"
	@echo "... _deps/juce-src/modules/juce_graphics/juce_graphics.s"
	@echo "... _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.o"
	@echo "... _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.i"
	@echo "... _deps/juce-src/modules/juce_gui_basics/juce_gui_basics.s"
	@echo "... _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.o"
	@echo "... _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.i"
	@echo "... _deps/juce-src/modules/juce_gui_extra/juce_gui_extra.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/stephane/Code/CL/2023/OctaSplit/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

